Repository pysal/access, pull requests merged in 2025-07, with the labels that each got.

#82 ruff access - part 4 + convert to `pytest`
  access/tests/test_access.py
  access/tests/test_datasets.py
  access/tests/test_euclidean.py
Labels: maint

#84 thread through the missing parameters in RAAM
  access/access.py
Labels: bug

#83 `ruff` access - part 5 + convert to `pytest`
  access/tests/test_floating_catchment_area.py
  access/tests/test_helpers.py
  access/tests/test_hospital_example.py
Labels: maint

#85 `ruff` access - part 6 + convert to `pytest`
  access/tests/test_misc.py
  access/tests/test_raam.py
  access/tests/test_weighted_catchment.py
  access/tests/test_weights.py
  access/tests/util.py
Labels: maint

#87 `ruff` access - part 7 + pandas warnings
  .pre-commit-config.yaml
  access/access.py
  access/fca.py
  notebooks/Generating and Plotting a Variety of Access Scores.ipynb
  notebooks/How to Read, Filter, and Convert Shapefiles to .geojson.ipynb
  notebooks/How to Subset the Travel Cost Matricies.ipynb
  notebooks/How to Use access to Compute Access Scores to Resources Given XY Coordinates Joined to Census Tracts.ipynb
  notebooks/How to Use access to Compute Access to Locations Given X Y Coordinates.ipynb
Labels: maint

#92 rename notebooks and clean up links in docs
  docs/index.rst
  docs/installation.rst
  docs/tutorials.rst
  notebooks/1_generating_and_plotting_access_scores.ipynb
  notebooks/2_subset_travel_cost_matrices.ipynb
  notebooks/3_read_filter_convert_shapefiles_to_geojson.ipynb
  notebooks/4_compute_access_scores.ipynb
  notebooks/5_compute_access_scores_joined_census_tracts.ipynb
Labels: documentation, maint

#93 remove `tools/gitcount.ipynb` - no longer used
  .github/workflows/upload_package.yml
  tools/gitcount.ipynb
Labels: maint
